name = "akbar-smarthome-api"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "D1_DB"
database_name = "akbar-smarthome-cf"
database_id = "148ef8ed-4d5f-4c07-90f2-7a497a6c865f"
migrations_dir = "server/database/migrations"